import DesklingTesting
import XCTest

/// Keeps `conformance/` in step with the Swift reference. The vectors are generated here and replayed by
/// `dotnet/Deskling.Core.Tests`; change one only by regenerating it (`scripts/conformance.sh`), never by hand.
final class ConformanceTests: XCTestCase {
    /// Set to 1 to regenerate the vectors in place (SwiftPM tests aren't sandboxed).
    static let writeFlag = "DESKLING_WRITE_CONFORMANCE"

    /// Folders owned by the generator.
    static let generatedFolders = [SchedulerVectors.directory]

    /// Every generated file, keyed by its path inside `conformance/`.
    static func generated() throws -> [String: Data] {
        try SchedulerVectors.files()
    }

    private func committedFiles(in folder: String) throws -> [String] {
        let url = ConformanceRoot.url.appendingPathComponent(folder)
        return try FileManager.default.contentsOfDirectory(atPath: url.path).filter { !$0.hasPrefix(".") }.sorted()
    }

    // MARK: Up to date

    func testVectorsAreUpToDate() throws {
        let dir = ConformanceRoot.url
        let generated = try Self.generated()
        let hint = "Regenerate with scripts/conformance.sh and commit the result."
        for (path, data) in generated.sorted(by: { $0.key < $1.key }) {
            let committed = try? Data(contentsOf: dir.appendingPathComponent(path))
            XCTAssertNotNil(committed, "conformance/\(path) is missing. \(hint)")
            if let committed { XCTAssertEqual(committed, data, "conformance/\(path) is stale. \(hint)") }
        }
        for folder in Self.generatedFolders {
            for name in try committedFiles(in: folder) where generated["\(folder)/\(name)"] == nil {
                XCTFail("conformance/\(folder)/\(name) isn't generated by any case. \(hint)")
            }
        }
    }

    // MARK: Replay

    /// Replays the committed vectors the way a port does: read the input, run the code, compare.
    func testCommittedVectorsReplay() throws {
        let dir = ConformanceRoot.url
        var problems: [String] = []
        for folder in Self.generatedFolders {
            for name in try committedFiles(in: folder) where name.hasSuffix(".json") {
                let data = try Data(contentsOf: dir.appendingPathComponent(folder).appendingPathComponent(name))
                problems += try SchedulerVectors.verify(data, file: "\(folder)/\(name)")
            }
        }
        XCTAssertEqual(problems, [], problems.joined(separator: "\n"))
    }

    // MARK: Regenerate

    /// Rewrites every generated folder in `conformance/` from the Swift reference.
    func testWriteVectors() throws {
        try XCTSkipUnless(
            ProcessInfo.processInfo.environment[Self.writeFlag] == "1",
            "Set \(Self.writeFlag)=1 to regenerate the conformance vectors.")
        let dir = ConformanceRoot.url
        for folder in Self.generatedFolders {
            try? FileManager.default.removeItem(at: dir.appendingPathComponent(folder))
        }
        for (path, data) in try Self.generated() {
            let url = dir.appendingPathComponent(path)
            try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
            try data.write(to: url)
        }
        print("Wrote conformance vectors to \(dir.path)")
    }
}
